- name: Determine available groups
  getent:
    database: group
  tags:
    - jenkins
    - admins

- name: Debian scenario
  block:
    - name: Installing packages
      apt:
        name: sudo,tmux,zsh
        state: present
        update_cache: yes
      tags:
        - sudo
    - name: Installing sudo aliases
      copy: 
        src: files/aliases.sudo
        dest: /etc/sudoers.d/aliases
        mode: 0440
    - import_tasks: admins.yml
      tags:
        - admins
    - name: Setting force_color_prompt=yes for admins user
      lineinfile:
        dest: /home/admins/.bashrc
        regexp: '^#force_color_prompt=yes'
        line: 'force_color_prompt=yes'
    - import_tasks: jenkins.yml
      tags:
        - jenkins
  vars:
    admin_group: sudo
  when: ansible_os_family == 'Debian'

- name: CenOS scenario
  block:
    - name: Installing sudo
      yum:
        name: sudo
        state: present
      tags:
        - sudo
    - name: Installing sudo aliases
      copy: 
        src: files/aliases.sudo
        dest: /etc/sudoers.d/aliases
        mode: 0440
    - import_tasks: admins.yml
      tags:
        - admins
    - import_tasks: jenkins.yml
      tags:
        - jenkins
  vars:
    admin_group: wheel
  when: ansible_facts['distribution'] == 'CentOS'
