- name:
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- import_tasks: centos.yml
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] >= "7"
  
- import_tasks: debian.yml
  when: ansible_facts['distribution'] == 'Debian'
