- name: Generating locales
  locale_gen:
    name: "{{ item }}"
  with_items:
    - ru_RU
    - ru_RU.UTF-8
  become: yes

- name: Installing dependencies
  apt:
    name:
      - curl
      - libltdl7
      - libpq-dev
      - ca-certificates
      - apt-transport-https
      - software-properties-common
    update_cache: yes
  become: yes

- name: Installing Docker CE
  apt:
    deb: https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_18.06.1~ce~3-0~ubuntu_amd64.deb
  become: yes

- name: Downloading and installing Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755
  become: yes

- name: Setting up Dockerd
  lineinfile:
    dest: /etc/default/docker
    line: 'DOCKER_OPTS="--exec-opt native.cgroupdriver=systemd"'
    state: present
    create: no
  become: yes
  register: service

- name: Setting up Docker service
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
    force: yes
  become: yes
  register: systemd
  with_items:
    - docker.service

- name: Reloading daemon
  systemd:
    name: docker
    daemon_reload: yes
  become: yes
  when: systemd.changed

- name: Restarting Dockerd
  service:
    name: docker
    state: restarted
  become: yes
  when: service.changed or systemd.changed
